const EXTENSION_MAP: Record<string, string> = {
  js: 'javascript',
  mjs: 'javascript',
  cjs: 'javascript',
  jsx: 'javascript',
  ts: 'typescript',
  tsx: 'typescript',
  py: 'python',
  pyw: 'python',
  rs: 'rust',
  go: 'go',
  html: 'html',
  htm: 'html',
  css: 'css',
  scss: 'scss',
  sass: 'sass',
  less: 'less',
  json: 'json',
  md: 'markdown',
  mdx: 'markdown',
  yml: 'yaml',
  yaml: 'yaml',
  toml: 'toml',
  ini: 'ini',
  cfg: 'ini',
  sh: 'shell',
  bash: 'shell',
  zsh: 'shell',
  ps1: 'powershell',
  sql: 'sql',
  xml: 'xml',
  svg: 'xml',
  cpp: 'cpp',
  cc: 'cpp',
  cxx: 'cpp',
  h: 'cpp',
  hpp: 'cpp',
  c: 'c',
  cs: 'csharp',
  java: 'java',
  kt: 'kotlin',
  swift: 'swift',
  rb: 'ruby',
  php: 'php',
  dart: 'dart',
  lua: 'lua',
  r: 'r',
  ex: 'elixir',
  exs: 'elixir',
  vue: 'vue',
  svelte: 'svelte',
}

export function getLanguageFromPath(filePath: string): string {
  const lastDot = filePath.lastIndexOf('.')
  if (lastDot <= 0 || lastDot === filePath.length - 1) return 'plaintext'
  const ext = filePath.slice(lastDot + 1).toLowerCase()
  return EXTENSION_MAP[ext] ?? 'plaintext'
}
