"""Settings API routes façade.

This module preserves backward compatibility by re-exporting all symbols
and the FastAPI APIRouter from the modularized routes.settings_pkg package:
- routes.settings_pkg.schemas: Pydantic schemas, payload and response dataclasses
- routes.settings_pkg.router_presets: Image and video generation presets and custom recipes
- routes.settings_pkg.router_hardware: Hardware limits, HF token/cache, llama.cpp path, VRAM budget
- routes.settings_pkg.router_providers_switch: Coding agents, OpenAI auto switch, model overrides, embeddings
- routes.settings_pkg.router_network: Preview sharing, rotate links, LAN access and remote access
- routes.settings_pkg.router_personalization: UI themes, colors, fonts, avatar and sidebar navigation
- routes.settings_pkg.router_debug: Debug log sources and log streaming
"""

from loggers import get_logger

logger = get_logger(__name__)

from routes.settings_pkg import (
    router,
    # Schemas & Classes
    ImageGenerationPresetParams,
    VideoGenerationPresetParams,
    MediaGenerationPreset,
    ImageGenerationPreset,
    VideoGenerationPreset,
    MediaGenerationPresetState,
    ImageGenerationPresetState,
    VideoGenerationPresetState,
    ImageGenerationPresetSettings,
    VideoGenerationPresetSettings,
    UploadLimitPayload,
    UploadLimitResponse,
    HuggingFaceTokenPayload,
    HuggingFaceTokenResponse,
    HelperPrecachePayload,
    HelperPrecacheResponse,
    ModelMemoryPayload,
    ModelMemoryResponse,
    VramBudgetPayload,
    VramBudgetResponse,
    HuggingFaceCachePayload,
    HuggingFaceCacheResponse,
    LlamaCppPathPayload,
    LlamaCppPathResponse,
    OpenAIAutoSwitchPayload,
    OpenAIAutoSwitchResponse,
    _MAX_VARIANT_SUFFIX_LEN,
    MAX_MODEL_OVERRIDE_KEY_LEN,
    MAX_GGUF_VARIANT_KEY_LEN,
    MAX_GPU_IDS,
    ModelOverridePayload,
    ModelOverridesResponse,
    _LAST_LOCAL_MODEL_CLOCK_SLACK_MS,
    LastLocalModelPayload,
    LastLocalModelResponse,
    CodingAgentsResponse,
    EmbeddingModelPayload,
    EmbeddingModelResponse,
    PreviewLinkRotateResponse,
    PreviewSharingPayload,
    PreviewSharingResponse,
    RemoteAccessAutoStartPayload,
    RemoteAccessResponse,
    LanAccessAutoStartPayload,
    LanAccessResponse,
    PersonalizationProfile,
    PersonalizationCustomColors,
    PersonalizationCustomColorModes,
    MAX_IMPORTED_FONTS,
    MAX_FONT_DATA_URL_LENGTH,
    MAX_TOTAL_FONT_DATA_URL_LENGTH,
    _FONT_NAME_FORBIDDEN,
    _check_font_name,
    _FONT_DATA_URL_PATTERN,
    PersonalizationImportedFont,
    SIDEBAR_MENU_ITEM_DEFAULTS,
    SIDEBAR_NAV_ITEM_DEFAULTS,
    MAX_SIDEBAR_NAV_INPUT_ITEMS,
    MAX_SIDEBAR_MENU_INPUT_ITEMS,
    PersonalizationSidebarMenuItem,
    _default_sidebar_menu,
    PersonalizationSidebarNavItem,
    _default_sidebar_nav,
    PersonalizationCustomization,
    PersonalizationAppearance,
    PersonalizationPayload,
    PersonalizationResponse,
    DebugLogSourceModel,
    DebugLogSourcesResponse,
    DebugLogResponse,
    # Presets Helpers & Endpoints
    _nested_model,
    _readable,
    _without_field_at_location,
    _validated_without_invalid_fields,
    _preserve_recovered_defaults,
    _validated_readable_model,
    _get_generation_preset_settings,
    get_image_generation_preset_settings,
    update_image_generation_preset_settings,
    get_video_generation_preset_settings,
    update_video_generation_preset_settings,
    _upsert_custom_generation_preset,
    upsert_custom_image_generation_preset,
    upsert_custom_video_generation_preset,
    delete_custom_generation_preset,
    # Hardware Helpers & Endpoints
    get_hugging_face_token,
    update_hugging_face_token,
    migrate_hugging_face_token,
    clear_hugging_face_token,
    _upload_limit_response,
    _helper_precache_response,
    _NO_LAUNCH,
    _active_launch_placement,
    _model_memory_reload_required,
    _model_memory_mlock_active,
    _model_memory_response,
    _vram_budget_reload_required,
    _vram_budget_response,
    _hugging_face_cache_response,
    _llama_cpp_path_reload_required,
    _llama_cpp_path_response,
    get_hugging_face_cache,
    update_hugging_face_cache,
    get_llama_cpp_path,
    update_llama_cpp_path,
    get_upload_limit,
    update_upload_limit,
    get_helper_precache,
    update_helper_precache,
    get_model_memory,
    update_model_memory,
    LAST_LOCAL_MODEL_SETTING_KEY,
    _LAST_LOCAL_MODEL_LOCK,
    _last_local_model_key,
    _read_last_local_model,
    get_last_local_model,
    update_last_local_model,
    get_vram_budget,
    update_vram_budget,
    # Providers Switch Helpers & Endpoints
    get_coding_agents,
    get_openai_auto_switch,
    update_openai_auto_switch,
    get_openai_auto_switch_overrides,
    _bare_model_id,
    _fallback_supplies_extra_args,
    _other_quants_remain,
    _legacy_standalone_gguf_key,
    _fill_target_id,
    _override_write_lock,
    _serialized_override_write,
    update_openai_auto_switch_override,
    _embedding_model_response,
    _ambient_hf_token,
    _llama_backend_active,
    _resolves_as_local_gguf,
    _local_gguf_backend_error,
    _hf_gguf_backend_error,
    get_embedding_model,
    update_embedding_model,
    reset_embedding_model,
    # Network Helpers & Endpoints
    rotate_preview_links,
    _require_ui_session,
    _remote_access_response,
    get_remote_access,
    start_remote_access_route,
    stop_remote_access_route,
    update_remote_access_auto_start,
    _lan_access_response,
    get_lan_access,
    start_lan_access_route,
    stop_lan_access_route,
    update_lan_access_auto_start,
    get_preview_sharing,
    update_preview_sharing,
    # Personalization Helpers & Endpoints
    _is_bundled_avatar_url,
    get_personalization_settings,
    _merge_personalization,
    update_personalization_settings,
    # Debug Logs Endpoints
    get_debug_log_sources,
    get_debug_log,
)
