export { createProvider } from './ai'
export { AIGateway, aiGateway } from './ai/gateway'
export { createChatService } from './chat'
export { createMCPClient } from './mcp'
export type { ChatService } from './chat'
export { extractMemory, isTrivialTurn, buildExtractionPrompt, parseExtractionResponse } from './memory/extractor'
export { writeExtractedMemory, findDuplicateEntry, updateTrustScore } from './memory/graph-writer'
export { computeGraphLayout, computeRelations, getNewNodePositions } from './memory/graph-layout'
export { configureVector, ensureVectorReady, indexInChroma, semanticSearch, buildMemoryContext } from './memory'
export type { SemanticSearchResult } from './memory'
