import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { chromium } from 'playwright';
const root = fileURLToPath(new URL('../desktop/frontend-spartan/', import.meta.url));
const requireFrontend = createRequire(root + 'package.json');
const { createServer } = await import(pathToFileURL(requireFrontend.resolve('vite')).href);
const server = await createServer({ root, configFile: root + 'vite.config.ts', server: {host:'127.0.0.1',port:0} });
let browser;
try {
  await server.listen();
  browser = await chromium.launch({headless:true,...(process.platform==='win32'?{channel:'msedge'}:{})});
  const page = await browser.newPage({viewport:{width:1280,height:900}});
  const errors=[];
  let navigations = 0;
  page.on('framenavigated', frame => { if (frame === page.mainFrame()) navigations++; });
  page.on('pageerror', error=>errors.push(error.message));
  await page.route('**/api/**', route=>new URL(route.request().url()).pathname.startsWith('/api/') ? route.fulfill({json:{projects:[]}}) : route.continue());
  await page.goto(server.resolvedUrls.local[0]+'tests/fixtures/preview-harness.html');
  const progress = page.getByRole('status').filter({hasText:'Informe.pdf'});
  assert.equal(await progress.getAttribute('aria-busy'),'true');
  await page.emulateMedia({reducedMotion:'reduce'});
  assert.equal(await progress.locator('.artifact-card-shimmer').evaluate(node=>getComputedStyle(node).animationName),'none');
  await page.getByRole('button',{name:'Abrir Word',exact:true}).click();
  await page.frameLocator('iframe').locator('section.docx').first().waitFor();
  await page.getByRole('button',{name:'Abrir PDF',exact:true}).click();
  await page.locator('.react-pdf__Page canvas').waitFor();
  await page.getByRole('button',{name:'Abrir hoja',exact:true}).click();
  await page.locator('#document-preview-content').getByText('Proyecto 1',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Abrir PDF',exact:true}).click();
  await page.locator('.react-pdf__Page canvas').waitFor();
  await page.getByRole('button',{name:'Abrir hoja',exact:true}).click();
  await page.locator('#document-preview-content').getByText('Proyecto 1',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Abrir notas',exact:true}).click();
  await page.locator('#document-preview-content').getByText('Documento de prueba',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Abrir Word',exact:true}).click();
  await page.frameLocator('iframe').locator('section.docx').first().waitFor();
  assert.deepEqual(errors,[]);
  assert.equal(navigations, 1, 'opening a lazy document viewer must not reload the application');
  await page.goto(server.resolvedUrls.local[0]+'tests/fixtures/python-tools-harness.html');
  const tool = page.locator('[data-slot="tool-fallback-root"]');
  await tool.waitFor();
  assert.equal(await tool.getByText('LIBRARY_PROBE_DETAILS', {exact:false}).count(),0);
  await tool.getByRole('button').first().click();
  await page.waitForFunction(() => document.body.textContent.includes('LIBRARY_PROBE_DETAILS'));
  await tool.getByRole('button').first().click();
  await page.waitForFunction(() => !document.body.textContent.includes('LIBRARY_PROBE_DETAILS'));
  assert.deepEqual(errors,[]);
  console.log('Document preview: cold open, Word, PDF, spreadsheet, Markdown and reopening passed.');
} finally { await browser?.close(); await server.close(); }
