import {chromium} from 'playwright';
import {mkdirSync} from 'node:fs';
const browser=await chromium.launch({headless:true,channel:'msedge'});
const page=await browser.newPage({viewport:{width:1280,height:900}});
const errors=[];
page.on('pageerror',error=>errors.push(error.message));
try {
  await page.goto('http://127.0.0.1:4173/');
  const announcement=page.getByRole('dialog');
  await announcement.waitFor();
  await announcement.getByText('Próxima actualización de Desktop',{exact:true}).waitFor();
  const download=announcement.getByRole('link',{name:'Descargar versión publicada v0.3.2'});
  if (!(await download.getAttribute('href')).includes('/v0.3.2/')) throw new Error('Published download points to the wrong version');
  await announcement.getByRole('button',{name:'Cerrar ventana'}).click();
  await page.locator('#novedades').scrollIntoViewIfNeeded();
  if(await page.locator('#novedades article').count()!==4) throw new Error('Upcoming desktop features are incomplete');
  if(await page.locator('a[href*="v0.3.1"]').count()) throw new Error('Landing still links to outdated downloads');
  mkdirSync('artifacts',{recursive:true});
  await page.locator('#novedades').screenshot({path:'artifacts/landing-desktop-news.png'});
  await page.reload();
  await page.getByRole('button',{name:/Novedades de Desktop/}).waitFor();
  if(await announcement.count()) throw new Error('Dismissed announcement reopens on reload');
  await page.getByRole('button',{name:/Novedades de Desktop/}).click();
  await announcement.waitFor();
  await announcement.getByRole('button',{name:'Cerrar ventana'}).click();
  await page.setViewportSize({width:390,height:844});
  await page.locator('#novedades').scrollIntoViewIfNeeded();
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)) throw new Error('Mobile landing overflows');
  await page.locator('#novedades').screenshot({path:'artifacts/landing-desktop-news-mobile.png'});
  if(errors.length) throw new Error(errors.join('\n'));
  console.log('Landing OK: upcoming announcement, published version links, persisted dismissal, mobile layout, no browser exceptions');
}finally{await browser.close();}
