import { Moon, Sun, Monitor } from 'lucide-react';
import { SettingsSection, SettingsGroupDivider } from '../../../../desktop/frontend-spartan/src/features/settings/components/settings-section';
import { DemoSettingRow, DemoSettingToggle } from './demo-setting-row';
import { DEFAULT_DEMO_PREFERENCES, useDemoPreferences } from './demo-preferences';
import { DESKTOP_PALETTES } from './desktop-palettes.generated';
import { Button } from './desktop-demo-button';
import { DemoSidebarCustomizer } from './demo-sidebar-customizer';

function swatchText(color: string) { const rgb = [1, 3, 5].map(index => parseInt(color.slice(index, index + 2), 16)); return rgb[0] * .299 + rgb[1] * .587 + rgb[2] * .114 > 160 ? '#262626' : '#ffffff'; }

export function DemoAppearanceSettings({ theme, onTheme, compact, onCompact, onReduceMotion }: { theme: 'light' | 'dark'; onTheme: (theme: 'light' | 'dark') => void; compact: boolean; onCompact: (value: boolean) => void; onReduceMotion: (value: boolean) => void }) {
  const { prefs, update } = useDemoPreferences();
  return <>
    <SettingsSection title="Idioma"><DemoSettingRow label="Idioma de la interfaz" description="Esta demostración está disponible en español."><select aria-label="Idioma de la demo" disabled value="es"><option value="es">Español</option></select></DemoSettingRow></SettingsSection>
    <SettingsSection title="Tema"><DemoSettingRow label="Esquema de color" description="Claro, oscuro o según el sistema."><div className="demo-settings-segmented"><button type="button" aria-pressed={prefs.themeMode === 'light'} onClick={() => { update({ themeMode: 'light' }); onTheme('light'); }}><Sun />Claro</button><button type="button" aria-pressed={prefs.themeMode === 'dark'} onClick={() => { update({ themeMode: 'dark' }); onTheme('dark'); }}><Moon />Oscuro</button><button type="button" aria-pressed={prefs.themeMode === 'system'} onClick={() => { update({ themeMode: 'system' }); onTheme(matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'); }}><Monitor />Sistema</button></div></DemoSettingRow>
      <DemoSettingRow label="Paleta de colores" description="Los colores proceden de las tres paletas del escritorio."><span /></DemoSettingRow>
      <div className="demo-palette-grid">{([{ id: 'standard', name: 'Estándar' }, { id: 'classic', name: 'Clásica' }, { id: 'minimal', name: 'Minimalista' }] as const).map(item => <button type="button" key={item.id} aria-label={`Paleta ${item.name}`} aria-pressed={prefs.palette === item.id} onClick={() => update({ palette: item.id })}><span className="demo-palette-mini" style={{ background: DESKTOP_PALETTES[item.id].light.bg }}><i style={{ background: DESKTOP_PALETTES[item.id].light.sidebar }} /><span><b /><b /><em style={{ background: DESKTOP_PALETTES[item.id].light.primary }} /></span></span>{item.name}</button>)}</div>
    </SettingsSection>
    <SettingsSection title={theme === 'light' ? 'Tema claro' : 'Tema oscuro'}>{([{ key: 'accent', label: 'Acento', token: 'primary' }, { key: 'background', label: 'Fondo', token: 'bg' }, { key: 'foreground', label: 'Primer plano', token: 'text' }] as const).map(item => <DemoSettingRow key={item.key} label={item.label}><label className="demo-color-swatch" style={{ background: prefs.colors[theme][item.key] || DESKTOP_PALETTES[prefs.palette][theme][item.token], color: swatchText(prefs.colors[theme][item.key] || DESKTOP_PALETTES[prefs.palette][theme][item.token]) }}><input type="color" aria-label={`Color ${item.label}`} value={prefs.colors[theme][item.key] || DESKTOP_PALETTES[prefs.palette][theme][item.token]} onChange={event => update({ colors: { ...prefs.colors, [theme]: { ...prefs.colors[theme], [item.key]: event.target.value } } })} /><span>{(prefs.colors[theme][item.key] || DESKTOP_PALETTES[prefs.palette][theme][item.token]).toUpperCase()}</span></label></DemoSettingRow>)}</SettingsSection>
    <SettingsGroupDivider />
    <SettingsSection title="Tipografía">{([{ key: 'uiFont', label: 'Fuente de la interfaz' }, { key: 'headingFont', label: 'Fuente de los títulos' }, { key: 'chatFont', label: 'Fuente del chat' }, { key: 'codeFont', label: 'Fuente del código' }] as const).map(item => <DemoSettingRow label={item.label} key={item.key}><select aria-label={item.label} value={prefs[item.key]} onChange={event => update({ [item.key]: event.target.value })}><option value="Inter Variable, system-ui, sans-serif">Inter Variable</option><option value="SpartaHellix, sans-serif">Hellix</option><option value="Figtree Variable, sans-serif">Figtree</option><option value="Space Grotesk Variable, sans-serif">Space Grotesk</option><option value="Georgia, serif">Georgia</option><option value="ui-monospace, monospace">Monoespaciada del sistema</option></select></DemoSettingRow>)}</SettingsSection>
    <SettingsGroupDivider />
    <DemoSettingRow label="Contraste" description="Intensidad de los bordes y del texto secundario."><div className="demo-contrast-control"><input aria-label="Contraste" type="range" min={0} max={100} value={prefs.contrast} onChange={event => update({ contrast: Number(event.target.value) })} /><output>{prefs.contrast}</output></div></DemoSettingRow>
    <SettingsSection title="Preferencias"><DemoSettingToggle label="Usar cursores de puntero" description="Cambia el cursor al pasar sobre elementos interactivos." checked={prefs.pointer} onChange={pointer => update({ pointer })} />
      <DemoSettingRow label="Reducir el movimiento" description="Reduce las animaciones decorativas o sigue la configuración del sistema."><div className="demo-settings-segmented">{([{ id: 'system', label: 'Sistema' }, { id: 'on', label: 'Activado' }, { id: 'off', label: 'Desactivado' }] as const).map(item => <button type="button" key={item.id} aria-pressed={prefs.motion === item.id} onClick={() => { update({ motion: item.id }); onReduceMotion(item.id === 'on' || item.id === 'system' && matchMedia('(prefers-reduced-motion: reduce)').matches); }}>{item.label}</button>)}</div></DemoSettingRow>
      <DemoSettingRow label="Tamaño de fuente de la interfaz" description="Ajusta el tamaño base en la demostración."><div className="demo-size-control"><input type="number" aria-label="Tamaño de fuente de la interfaz" min={12} max={20} value={prefs.uiSize} onChange={event => update({ uiSize: Math.max(12, Math.min(20, Number(event.target.value) || 15)) })} /><span>px</span></div></DemoSettingRow>
      <DemoSettingRow label="Tamaño de fuente del código" description="Ajusta el tamaño de los bloques de código."><div className="demo-size-control"><input type="number" aria-label="Tamaño de fuente del código" min={10} max={20} value={prefs.codeSize} onChange={event => update({ codeSize: Math.max(10, Math.min(20, Number(event.target.value) || 13)) })} /><span>px</span></div></DemoSettingRow>
      <DemoSettingToggle label="Suavizado de fuentes" description="Usa antialiasing para suavizar el texto." checked={prefs.smoothing} onChange={smoothing => update({ smoothing })} />
      <DemoSettingToggle label="Fijar la barra lateral por defecto" description="Mantén la barra expandida en lugar de contraerla a iconos." checked={!compact} onChange={value => onCompact(!value)} />
    </SettingsSection>
    <SettingsSection title="Navegación de la barra lateral" description="Fija y reordena las secciones. Las demás pasan al menú Más. Arrastra el asa o usa sus flechas arriba y abajo."><DemoSidebarCustomizer /></SettingsSection>
    <Button variant="outline" onClick={() => { update({ palette: 'standard', colors: DEFAULT_DEMO_PREFERENCES.colors, uiFont: DEFAULT_DEMO_PREFERENCES.uiFont, headingFont: DEFAULT_DEMO_PREFERENCES.headingFont, chatFont: DEFAULT_DEMO_PREFERENCES.chatFont, codeFont: DEFAULT_DEMO_PREFERENCES.codeFont, uiSize: 15, codeSize: 13, contrast: 50, pointer: false, smoothing: true, motion: 'system', navPins: DEFAULT_DEMO_PREFERENCES.navPins, navOrder: DEFAULT_DEMO_PREFERENCES.navOrder }); onCompact(false); onReduceMotion(matchMedia('(prefers-reduced-motion: reduce)').matches); }}>Restablecer personalización</Button>
  </>;
}
