import type { ModelHubItem } from './types'

export const HUGGING_FACE_CATALOG: ModelHubItem[] = [
  {
    id: 'deepseek-v4-pro-0813',
    name: 'unsloth/DeepSeek-V4-Pro-0813-GGUF',
    displayName: 'DeepSeek-V4-Pro-0813-GGUF',
    author: 'unsloth',
    authorVerified: true,
    vendor: 'deepseek',
    description: 'DeepSeek-V4-Pro-0813 is a 1.57T parameter model with 48B active parameters per token, featuring Unsloth Dynamic 2.0 quantizations for extreme accuracy and low VRAM inference.',
    category: 'conversational',
    format: 'GGUF',
    size: '850 GB',
    params: '1573.0B (48B active)',
    vramReqQ4: '~28 GB VRAM (UD-Q4_K_XL)',
    vramReqQ8: '~52 GB VRAM',
    contextWindow: '128k tokens',
    capabilities: { reasoning: true, code: true, tools: true, vision: false },
    likes: '55',
    downloads: '23.0K',
    updatedAt: '5d ago',
    releaseDate: 'Aug 2028',
    license: 'mit',
    tags: ['General', 'Conversational', 'Base deepseek-ai/DeepSeek-V4-Pro-0813'],
    quants: [
      { name: 'UD-Q4_K_XL • GGUF', size: '850 GB', format: 'GGUF', recommended: true },
      { name: 'UD-Q8_0 • GGUF', size: '1.45 TB', format: 'GGUF' },
      { name: 'UD-Q5_K_M • GGUF', size: '990 GB', format: 'GGUF' },
      { name: 'UD-IQ4_XS • GGUF', size: '720 GB', format: 'GGUF' },
      { name: 'Q4_K_M • GGUF', size: '840 GB', format: 'GGUF' },
    ],
    guideTitle: 'Read our How to Run DeepSeek-V4 Guide!',
    guideNote: 'Unsloth Dynamic 2.0 achieves superior accuracy & outperforms other leading quants.',
    bulletPoints: [
      'See our DeepSeek-V4 guide for quantization analysis and run instructions.',
      'DeepSeek-V4-Pro-0813 is a 1.57T parameter model with 48B active parameters per token, so it needs substantially more memory than DeepSeek-V4-Flash-0731.',
      'For DeepSeek-V4-Flash-0731 GGUFs, see unsloth/DeepSeek-V4-Flash-0731-GGUF.',
      'Quants are uploaded to this repository as they finish converting.',
    ],
    externalLinks: [
      { label: 'DeepSeek Homepage', url: 'https://deepseek.com' },
      { label: 'Chat DeepSeek V4', url: 'https://chat.deepseek.com' },
      { label: 'HuggingFace Repo', url: 'https://huggingface.co/unsloth/DeepSeek-V4-Pro-0813-GGUF' },
    ],
    huggingFaceUrl: 'https://huggingface.co/unsloth/DeepSeek-V4-Pro-0813-GGUF',
    ollamaCommand: 'ollama run deepseek-v4:pro',
    vllmCommand: 'vllm serve unsloth/DeepSeek-V4-Pro-0813-GGUF --port 8000',
    downloadCommand: 'huggingface-cli download unsloth/DeepSeek-V4-Pro-0813-GGUF --local-dir ~/.sparta/models',
    localPath: '~/.sparta/models\\DeepSeek-V4-Pro-0813-UD-Q4_K_XL.gguf',
    isLocalAvailable: false,
  },
  {
    id: 'qwen-3.8-27b',
    name: 'unsloth/Qwen3.8-27B-GGUF',
    displayName: 'Qwen3.8-27B-GGUF',
    author: 'unsloth',
    authorVerified: true,
    vendor: 'qwen',
    description: 'Qwen 3.8 27B quantizado con Unsloth Dynamic Quants para programación de precisión, llamadas a herramientas complejas y razonamiento multi-paso.',
    category: 'code',
    format: 'GGUF',
    size: '16.8 GB',
    params: '27.4B',
    vramReqQ4: '~17.5 GB VRAM',
    vramReqQ8: '~30.2 GB VRAM',
    contextWindow: '128k tokens',
    capabilities: { reasoning: true, code: true, tools: true, vision: false },
    likes: '1.6K',
    downloads: '4.3M',
    updatedAt: '1h ago',
    releaseDate: 'Aug 2026',
    license: 'apache-2.0',
    tags: ['Coding', 'Reasoning', 'Base Qwen/Qwen3.8-27B'],
    quants: [
      { name: 'UD-Q4_K_M • GGUF', size: '16.8 GB', format: 'GGUF', recommended: true },
      { name: 'UD-Q8_0 • GGUF', size: '28.9 GB', format: 'GGUF' },
      { name: 'UD-IQ3_M • GGUF', size: '12.4 GB', format: 'GGUF' },
    ],
    guideTitle: 'Read our How to Run Qwen 3.8 Guide!',
    guideNote: 'Optimizado con kernels Triton de Unsloth con velocidad de tokenización 2.5x superior.',
    bulletPoints: [
      'Soporte completo para Function Calling estructurado JSON nativo.',
      'Excelente benchmark de generación y depuración de código en Python, Rust y TypeScript.',
      'Compatible con Ollama, vLLM y LLaMA.cpp en GPU NVIDIA y Apple Silicon.',
    ],
    externalLinks: [
      { label: 'Qwen AI Official', url: 'https://qwenlm.github.io' },
      { label: 'HuggingFace Repo', url: 'https://huggingface.co/unsloth/Qwen3.8-27B-GGUF' },
    ],
    huggingFaceUrl: 'https://huggingface.co/unsloth/Qwen3.8-27B-GGUF',
    ollamaCommand: 'ollama run qwen3.8:27b',
    vllmCommand: 'vllm serve unsloth/Qwen3.8-27B-GGUF --port 8000',
    downloadCommand: 'huggingface-cli download unsloth/Qwen3.8-27B-GGUF --local-dir ~/.sparta/models',
    localPath: '~/.sparta/models\\qwen3.8-27b-q4_k_m.gguf',
    isLocalAvailable: true,
  },
  {
    id: 'nvidia-nemotron-3.5-30b',
    name: 'unsloth/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-GGUF',
    displayName: 'NVIDIA-Nemotron-3.5-Lightning-30B-A3B-GGUF',
    author: 'unsloth',
    authorVerified: true,
    vendor: 'nvidia',
    description: 'NVIDIA Nemotron 3.5 Lightning 30B con arquitectura A3B optimizada para agentes autónomos y razonamiento ultra-rápido en GPUs Tensor.',
    category: 'reasoning',
    format: 'GGUF',
    size: '18.4 GB',
    params: '30.1B',
    vramReqQ4: '~19.0 GB VRAM',
    vramReqQ8: '~32.5 GB VRAM',
    contextWindow: '64k tokens',
    capabilities: { reasoning: true, code: true, tools: true, vision: false },
    likes: '75',
    downloads: '101.0K',
    updatedAt: '6d ago',
    releaseDate: 'Jul 2026',
    license: 'nvidia-open',
    tags: ['Agentic', 'Lightning Infe', 'Base nvidia/Nemotron-3.5-30B'],
    quants: [
      { name: 'UD-Q4_K_M • GGUF', size: '18.4 GB', format: 'GGUF', recommended: true },
      { name: 'UD-Q8_0 • GGUF', size: '31.2 GB', format: 'GGUF' },
    ],
    guideTitle: 'Run Nemotron 3.5 Lightning with TensorRT-LLM',
    guideNote: 'Capacidades de planificación de agentes autónomos validadas en SWE-bench.',
    bulletPoints: [
      'Destilado con técnicas de alineamiento RLHF propietarias de NVIDIA.',
      'Soporte nativo de llamada recursiva de herramientas y flujos MCP multi-paso.',
    ],
    externalLinks: [
      { label: 'NVIDIA Developer', url: 'https://developer.nvidia.com' },
      { label: 'HuggingFace Repo', url: 'https://huggingface.co/unsloth/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-GGUF' },
    ],
    huggingFaceUrl: 'https://huggingface.co/unsloth/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-GGUF',
    ollamaCommand: 'ollama run nemotron-lightning:30b',
    vllmCommand: 'vllm serve unsloth/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-GGUF --port 8000',
    downloadCommand: 'huggingface-cli download unsloth/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-GGUF --local-dir ~/.sparta/models',
    isLocalAvailable: false,
  },
  {
    id: 'qwen-3.8-2.4t-a95b',
    name: 'unsloth/Qwen3.8-2.4T-A95B-GGUF',
    displayName: 'Qwen3.8-2.4T-A95B-GGUF',
    author: 'unsloth',
    authorVerified: true,
    vendor: 'qwen',
    description: 'Qwen 3.8 Mixture of Experts (MoE) 2.4T de parámetros totales con 95B activos por token.',
    category: 'reasoning',
    format: 'GGUF',
    size: '56.2 GB',
    params: '95B (Active)',
    vramReqQ4: '~58.0 GB VRAM',
    vramReqQ8: '~98.0 GB VRAM',
    contextWindow: '128k tokens',
    capabilities: { reasoning: true, code: true, tools: true, vision: false },
    likes: '105',
    downloads: '16.6K',
    updatedAt: '6d ago',
    releaseDate: 'Jul 2026',
    license: 'apache-2.0',
    tags: ['MoE', 'High Reasoning', 'Base Qwen/Qwen3.8-MoE'],
    quants: [
      { name: 'UD-Q4_K_M • GGUF', size: '56.2 GB', format: 'GGUF', recommended: true },
      { name: 'UD-IQ3_M • GGUF', size: '42.8 GB', format: 'GGUF' },
    ],
    guideTitle: 'How to Distribute Qwen 3.8 MoE on Dual GPUs',
    guideNote: 'Excelente balance entre capacidad de modelo frontera y consumo de VRAM con Dynamic Quants.',
    bulletPoints: [
      'Arquitectura MoE con 8 expertos por capa y enrutamiento top-2.',
      'Soporte para inferencia distribuida en multi-GPU o CPU Offloading.',
    ],
    externalLinks: [
      { label: 'Qwen AI', url: 'https://qwenlm.github.io' },
    ],
    huggingFaceUrl: 'https://huggingface.co/unsloth/Qwen3.8-2.4T-A95B-GGUF',
    ollamaCommand: 'ollama run qwen3.8:a95b',
    vllmCommand: 'vllm serve unsloth/Qwen3.8-2.4T-A95B-GGUF --port 8000',
    downloadCommand: 'huggingface-cli download unsloth/Qwen3.8-2.4T-A95B-GGUF --local-dir ~/.sparta/models',
    isLocalAvailable: false,
  },
  {
    id: 'muse-glimmer-30b',
    name: 'unsloth/Muse-Glimmer-30B-GGUF',
    displayName: 'Muse-Glimmer-30B-GGUF',
    author: 'unsloth',
    authorVerified: true,
    vendor: 'mistral',
    description: 'Modelo creativo y conversacional con entonación natural, síntesis literaria y comprensión contextual profunda.',
    category: 'conversational',
    format: 'GGUF',
    size: '18.1 GB',
    params: '30B',
    vramReqQ4: '~19.2 GB VRAM',
    vramReqQ8: '~31.5 GB VRAM',
    contextWindow: '64k tokens',
    capabilities: { reasoning: true, code: false, tools: true, vision: false },
    likes: '487',
    downloads: '818.8K',
    updatedAt: '8d ago',
    releaseDate: 'Jun 2026',
    license: 'mit',
    tags: ['Conversational', 'Creative', 'Literature'],
    quants: [
      { name: 'UD-Q4_K_M • GGUF', size: '18.1 GB', format: 'GGUF', recommended: true },
      { name: 'UD-Q8_0 • GGUF', size: '30.8 GB', format: 'GGUF' },
    ],
    guideTitle: 'Fine-tuning Muse Glimmer with Unsloth LoRA',
    guideNote: 'Entrenado con datasets curados para diálogos fluidos sin repetitividad ni degradación de contexto.',
    bulletPoints: [
      'Generación de lenguaje natural excepcionalmente empática y estructurada.',
      'Soporte multi-idioma nativo incluyendo español, inglés, alemán y japonés.',
    ],
    externalLinks: [
      { label: 'HuggingFace Repo', url: 'https://huggingface.co/unsloth/Muse-Glimmer-30B-GGUF' },
    ],
    huggingFaceUrl: 'https://huggingface.co/unsloth/Muse-Glimmer-30B-GGUF',
    ollamaCommand: 'ollama run muse-glimmer:30b',
    downloadCommand: 'huggingface-cli download unsloth/Muse-Glimmer-30B-GGUF --local-dir ~/.sparta/models',
    isLocalAvailable: false,
  },
  {
    id: 'minimax-h3',
    name: 'unsloth/MiniMax-H3-GGUF',
    displayName: 'MiniMax-H3-GGUF',
    author: 'unsloth',
    authorVerified: true,
    vendor: 'meta',
    description: 'Modelo de contexto masivo de 1M tokens con recuperación de información precisa Needle-in-a-Haystack.',
    category: 'reasoning',
    format: 'GGUF',
    size: '22.4 GB',
    params: '36B',
    vramReqQ4: '~23.5 GB VRAM',
    vramReqQ8: '~38.0 GB VRAM',
    contextWindow: '1M tokens',
    capabilities: { reasoning: true, code: true, tools: true, vision: false },
    likes: '181',
    downloads: '247.6K',
    updatedAt: '5d ago',
    releaseDate: 'May 2026',
    license: 'apache-2.0',
    tags: ['Long Context', '1M Tokens', 'RAG'],
    quants: [
      { name: 'UD-Q4_K_M • GGUF', size: '22.4 GB', format: 'GGUF', recommended: true },
      { name: 'UD-IQ3_S • GGUF', size: '16.5 GB', format: 'GGUF' },
    ],
    guideTitle: 'Processing 1M Tokens Locally with FlashAttention-3',
    guideNote: 'Compresión de KV-Cache inteligente para análisis de repositorios y libros completos.',
    bulletPoints: [
      '100% de precisión en pruebas de aguja en pajar hasta 1.000.000 de tokens.',
      'Ideal para análisis de bases de código completas en Sparta Agent.',
    ],
    externalLinks: [
      { label: 'MiniMax AI', url: 'https://minimax.io' },
    ],
    huggingFaceUrl: 'https://huggingface.co/unsloth/MiniMax-H3-GGUF',
    ollamaCommand: 'ollama run minimax-h3',
    downloadCommand: 'huggingface-cli download unsloth/MiniMax-H3-GGUF --local-dir ~/.sparta/models',
    isLocalAvailable: false,
  },
  {
    id: 'deepseek-v4-flash-0731',
    name: 'unsloth/DeepSeek-V4-Flash-0731-GGUF',
    displayName: 'DeepSeek-V4-Flash-0731-GGUF',
    author: 'unsloth',
    authorVerified: true,
    vendor: 'deepseek',
    description: 'Versión ultra-rápida y ligera de DeepSeek V4 diseñada para respuesta inmediata con menos de 8GB de VRAM.',
    category: 'conversational',
    format: 'GGUF',
    size: '7.8 GB',
    params: '12B',
    vramReqQ4: '~8.2 GB VRAM',
    vramReqQ8: '~13.5 GB VRAM',
    contextWindow: '64k tokens',
    capabilities: { reasoning: true, code: true, tools: true, vision: false },
    likes: '699',
    downloads: '345.5K',
    updatedAt: '13d ago',
    releaseDate: 'Jul 2026',
    license: 'mit',
    tags: ['Ultra Fast', 'Low VRAM', 'Base DeepSeek-V4-Flash'],
    quants: [
      { name: 'UD-Q4_K_M • GGUF', size: '7.8 GB', format: 'GGUF', recommended: true },
      { name: 'UD-Q8_0 • GGUF', size: '12.9 GB', format: 'GGUF' },
      { name: 'UD-IQ3_XS • GGUF', size: '5.6 GB', format: 'GGUF' },
    ],
    guideTitle: 'Run DeepSeek-V4-Flash in Any Laptop GPU',
    guideNote: 'Inferencia instantánea a más de 95 tokens/segundo en RTX 3060/4060.',
    bulletPoints: [
      'Optimización de latencia de primer token (TTFT) inferior a 80ms.',
      'Excelente para autocompletado en vivo y agentes conversacionales interactivos.',
    ],
    externalLinks: [
      { label: 'DeepSeek Homepage', url: 'https://deepseek.com' },
      { label: 'HuggingFace Repo', url: 'https://huggingface.co/unsloth/DeepSeek-V4-Flash-0731-GGUF' },
    ],
    huggingFaceUrl: 'https://huggingface.co/unsloth/DeepSeek-V4-Flash-0731-GGUF',
    ollamaCommand: 'ollama run deepseek-v4:flash',
    downloadCommand: 'huggingface-cli download unsloth/DeepSeek-V4-Flash-0731-GGUF --local-dir ~/.sparta/models',
    localPath: '~/.sparta/models\\deepseek-v4-flash-q4_k_m.gguf',
    isLocalAvailable: true,
  },
  {
    id: 'kimi-k3',
    name: 'unsloth/Kimi-K3-GGUF',
    displayName: 'Kimi-K3-GGUF',
    author: 'unsloth',
    authorVerified: true,
    vendor: 'kimi',
    description: 'Moonshot AI Kimi K3 con capacidades excepcionales de seguimiento de instrucciones complejas y búsqueda web.',
    category: 'reasoning',
    format: 'GGUF',
    size: '14.5 GB',
    params: '22B',
    vramReqQ4: '~15.2 GB VRAM',
    vramReqQ8: '~24.0 GB VRAM',
    contextWindow: '200k tokens',
    capabilities: { reasoning: true, code: true, tools: true, vision: false },
    likes: '355',
    downloads: '446.7K',
    updatedAt: '12d ago',
    releaseDate: 'Jun 2026',
    license: 'apache-2.0',
    tags: ['Instruction Following', 'Search Agent', 'Moonshot AI'],
    quants: [
      { name: 'UD-Q4_K_M • GGUF', size: '14.5 GB', format: 'GGUF', recommended: true },
      { name: 'UD-Q8_0 • GGUF', size: '23.6 GB', format: 'GGUF' },
    ],
    guideTitle: 'Integrating Kimi K3 with Local Tools in Sparta',
    guideNote: 'Precisión sobresaliente en la invocación de herramientas MCP estructuradas.',
    bulletPoints: [
      'Compatible con los conectores MCP de Notion, Google Workspace y Filesystem.',
      'Soporte multilingüe optimizado.',
    ],
    externalLinks: [
      { label: 'Moonshot AI', url: 'https://moonshot.ai' },
    ],
    huggingFaceUrl: 'https://huggingface.co/unsloth/Kimi-K3-GGUF',
    ollamaCommand: 'ollama run kimi:k3',
    downloadCommand: 'huggingface-cli download unsloth/Kimi-K3-GGUF --local-dir ~/.sparta/models',
    isLocalAvailable: false,
  },
  {
    id: 'deepseek-r1-8b',
    name: 'deepseek-ai/DeepSeek-R1-Distill-Qwen-8B',
    displayName: 'DeepSeek-R1-Distill-Qwen-8B-GGUF',
    author: 'unsloth',
    authorVerified: true,
    vendor: 'deepseek',
    description: 'Modelo de razonamiento matemático y de código de alto rendimiento destilado desde DeepSeek-R1 671B.',
    category: 'reasoning',
    format: 'GGUF',
    size: '4.9 GB',
    params: '8B',
    vramReqQ4: '~5.5 GB VRAM',
    vramReqQ8: '~9.2 GB VRAM',
    contextWindow: '128k tokens',
    capabilities: { reasoning: true, code: true, tools: true, vision: false },
    likes: '8.4K',
    downloads: '1.8M',
    updatedAt: '2d ago',
    releaseDate: 'Jan 2025',
    license: 'mit',
    tags: ['Chain of Thought', 'Reasoning', 'Math & Code'],
    quants: [
      { name: 'UD-Q4_K_M • GGUF', size: '4.9 GB', format: 'GGUF', recommended: true },
      { name: 'UD-Q8_0 • GGUF', size: '8.5 GB', format: 'GGUF' },
      { name: 'UD-IQ3_M • GGUF', size: '3.8 GB', format: 'GGUF' },
    ],
    guideTitle: 'How to Run DeepSeek R1 Distill Locally',
    guideNote: 'Pensamiento profundo transparente <think>...</think> para resolución de problemas lógicos.',
    bulletPoints: [
      'Razonamiento paso a paso destilado del modelo de 671B.',
      'Funciona perfectamente en cualquier GPU de 6GB o con CPU Offloading.',
    ],
    externalLinks: [
      { label: 'DeepSeek AI', url: 'https://deepseek.com' },
      { label: 'HuggingFace Repo', url: 'https://huggingface.co/unsloth/DeepSeek-R1-Distill-Qwen-8B-GGUF' },
    ],
    huggingFaceUrl: 'https://huggingface.co/unsloth/DeepSeek-R1-Distill-Qwen-8B-GGUF',
    ollamaCommand: 'ollama run deepseek-r1:8b',
    vllmCommand: 'vllm serve unsloth/DeepSeek-R1-Distill-Qwen-8B-GGUF --port 8000',
    downloadCommand: 'huggingface-cli download unsloth/DeepSeek-R1-Distill-Qwen-8B-GGUF --local-dir ~/.sparta/models',
    localPath: '~/.sparta/models\\deepseek-r1-8b-q4_k_m.gguf',
    isLocalAvailable: true,
  },
  {
    id: 'qwen-2.5-coder-32b',
    name: 'Qwen/Qwen2.5-Coder-32B-Instruct',
    displayName: 'Qwen2.5-Coder-32B-Instruct-GGUF',
    author: 'unsloth',
    authorVerified: true,
    vendor: 'qwen',
    description: 'El modelo de código abierto líder para refactorización, depuración, agentes y generación fullstack.',
    category: 'code',
    format: 'GGUF',
    size: '19.8 GB',
    params: '32.5B',
    vramReqQ4: '~20.5 GB VRAM',
    vramReqQ8: '~34.0 GB VRAM',
    contextWindow: '128k tokens',
    capabilities: { reasoning: true, code: true, tools: true, vision: false },
    likes: '4.2K',
    downloads: '1.2M',
    updatedAt: '3d ago',
    releaseDate: 'Nov 2024',
    license: 'apache-2.0',
    tags: ['Coding', 'Fullstack', 'Agentic'],
    quants: [
      { name: 'UD-Q4_K_M • GGUF', size: '19.8 GB', format: 'GGUF', recommended: true },
      { name: 'UD-Q8_0 • GGUF', size: '34.5 GB', format: 'GGUF' },
    ],
    guideTitle: 'Fullstack Coding with Qwen 2.5 Coder 32B',
    guideNote: 'Capacidad de nivel GPT-4o en generación y análisis de repositorios completos.',
    bulletPoints: [
      'Soporte para más de 92 lenguajes de programación.',
      'Capacidad para refactorizar proyectos enteros y generar tests unitarios.',
    ],
    externalLinks: [
      { label: 'Qwen AI', url: 'https://qwenlm.github.io' },
    ],
    huggingFaceUrl: 'https://huggingface.co/unsloth/Qwen2.5-Coder-32B-Instruct-GGUF',
    ollamaCommand: 'ollama run qwen2.5-coder:32b',
    vllmCommand: 'vllm serve Qwen/Qwen2.5-Coder-32B-Instruct --gpu-memory-utilization 0.95',
    downloadCommand: 'huggingface-cli download unsloth/Qwen2.5-Coder-32B-Instruct-GGUF --local-dir ~/.sparta/models',
    localPath: '~/.sparta/models\\qwen-coder-32b-q8_0.gguf',
    isLocalAvailable: true,
  },
  {
    id: 'llama-3.3-70b',
    name: 'meta-llama/Llama-3.3-70B-Instruct',
    displayName: 'Llama-3.3-70B-Instruct-GGUF',
    author: 'unsloth',
    authorVerified: true,
    vendor: 'meta',
    description: 'Modelo insignia de Meta para tareas complejas de razonamiento general, análisis de datos y creación de software.',
    category: 'general',
    format: 'GGUF',
    size: '39.4 GB',
    params: '70.6B',
    vramReqQ4: '~41.0 GB VRAM',
    vramReqQ8: '~72.0 GB VRAM',
    contextWindow: '128k tokens',
    capabilities: { reasoning: true, code: true, tools: true, vision: false },
    likes: '6.1K',
    downloads: '2.5M',
    updatedAt: '4d ago',
    releaseDate: 'Dec 2024',
    license: 'llama3.3',
    tags: ['General', 'Flagship', 'Meta AI'],
    quants: [
      { name: 'UD-Q4_K_M • GGUF', size: '39.4 GB', format: 'GGUF', recommended: true },
      { name: 'UD-Q8_0 • GGUF', size: '71.8 GB', format: 'GGUF' },
      { name: 'UD-IQ3_M • GGUF', size: '31.2 GB', format: 'GGUF' },
    ],
    guideTitle: 'Running Llama 3.3 70B with 4-bit BnB / Unsloth',
    guideNote: 'Calidad comparable a Llama 3.1 405B en la mayoría de benchmarks.',
    bulletPoints: [
      'Capacidades multilingües avanzadas y análisis contextual profundo.',
      'Soporte completo para herramientas e integración de agentes.',
    ],
    externalLinks: [
      { label: 'Meta AI', url: 'https://llama.meta.com' },
    ],
    huggingFaceUrl: 'https://huggingface.co/unsloth/Llama-3.3-70B-Instruct-GGUF',
    ollamaCommand: 'ollama run llama3.3:70b',
    vllmCommand: 'vllm serve unsloth/Llama-3.3-70B-Instruct-GGUF --port 8000',
    downloadCommand: 'huggingface-cli download unsloth/Llama-3.3-70B-Instruct-GGUF --local-dir ~/.sparta/models',
    localPath: '~/.sparta/models\\llama-3.3-70b.gguf',
    isLocalAvailable: true,
  },
]
