declare module 'lucide-react' {
  import { FC, SVGProps } from 'react'

  export interface IconProps extends SVGProps<SVGSVGElement> {
    size?: number | string
    absoluteStrokeWidth?: boolean
    color?: string
    strokeWidth?: number
    className?: string
    children?: never
  }

  export type Icon = FC<IconProps>

  export const Plus: Icon
  export const Search: Icon
  export const X: Icon
  export const MessageSquare: Icon
  export const Zap: Icon
  export const Plug: Icon
  export const Hash: Icon
  export const Brain: Icon
  export const Settings: Icon
  export const SlidersHorizontal: Icon
  export const Bot: Icon
  export const ShieldOff: Icon
  export const ChevronDown: Icon
  export const ChevronRight: Icon
  export const ChevronLeft: Icon
  export const ChevronUp: Icon
  export const Check: Icon
  export const Copy: Icon
  export const Edit: Icon
  export const Trash: Icon
  export const Trash2: Icon
  export const MoreHorizontal: Icon
  export const MoreVertical: Icon
  export const Menu: Icon
  export const Sun: Icon
  export const Moon: Icon
  export const Github: Icon
  export const Globe: Icon
  export const ExternalLink: Icon
  export const Download: Icon
  export const Upload: Icon
  export const RefreshCw: Icon
  export const RefreshCcw: Icon
  export const AlertCircle: Icon
  export const AlertTriangle: Icon
  export const Info: Icon
  export const HelpCircle: Icon
  export const Loader2: Icon
  export const Loader: Icon
  export const Sparkles: Icon
  export const Star: Icon
  export const Heart: Icon
  export const ThumbsUp: Icon
  export const ThumbsDown: Icon
  export const Send: Icon
  export const ArrowUp: Icon
  export const ArrowDown: Icon
  export const ArrowLeft: Icon
  export const ArrowRight: Icon
  export const Maximize: Icon
  export const Minimize: Icon
  export const Minimize2: Icon
  export const Maximize2: Icon
  export const Pin: Icon
  export const PinOff: Icon
  export const Filter: Icon
  export const Folder: Icon
  export const FolderOpen: Icon
  export const File: Icon
  export const FileText: Icon
  export const Terminal: Icon
  export const Code: Icon
  export const Database: Icon
  export const Server: Icon
  export const Cpu: Icon
  export const Monitor: Icon
  export const Smartphone: Icon
  export const Tablet: Icon
  export const Play: Icon
  export const Pause: Icon
  export const Stop: Icon
  export const SkipBack: Icon
  export const SkipForward: Icon
  export const Volume: Icon
  export const Volume2: Icon
  export const VolumeX: Icon
  export const Mic: Icon
  export const MicOff: Icon
  export const Camera: Icon
  export const Image: Icon
  export const Paperclip: Icon
  export const Link: Icon
  export const Unlink: Icon
  export const Lock: Icon
  export const Unlock: Icon
  export const Eye: Icon
  export const EyeOff: Icon
  export const Wifi: Icon
  export const WifiOff: Icon
  export const Cloud: Icon
  export const CloudOff: Icon
  export const Book: Icon
  export const BookOpen: Icon
  export const Bookmark: Icon
  export const Clock: Icon
  export const Calendar: Icon
  export const Bell: Icon
  export const BellOff: Icon
  export const Shield: Icon
  export const ShieldAlert: Icon
  export const ShieldOff: Icon
  export const Ban: Icon
  export const Bug: Icon
  export const FlaskConical: Icon
  export const Atom: Icon
  export const Orbit: Icon
  export const Siren: Icon
  export const Layers: Icon
  export const LayoutDashboard: Icon
  export const PanelLeft: Icon
  export const PanelRight: Icon
  export const PanelTop: Icon
  export const PanelBottom: Icon
  export const Sidebar: Icon
  export const Grid3X3: Icon
  export const List: Icon
  export const Columns: Icon
  export const Rows: Icon
  export const Tags: Icon
  export const Tag: Icon
  export const GripVertical: Icon
  export const GripHorizontal: Icon
  export const Grip: Icon
  export const PanelLeftOpen: Icon
  export const PanelLeftClose: Icon
  export const PanelRightOpen: Icon
  export const PanelRightClose: Icon
  export const Webhook: Icon
  export const Workflow: Icon
  export const Cable: Icon
  export const Usb: Icon
  export const Globe2: Icon
  export const Network: Icon
  export const Radio: Icon
  export const RadioTower: Icon
  export const AppWindow: Icon
  export const Bot: Icon
  export const MessageCircle: Icon
  export const MessagesSquare: Icon
  export const MessageSquarePlus: Icon
  export const MessageSquareX: Icon
  export const MessageSquareDashed: Icon
  export const MessageSquareQuote: Icon
  export const Reply: Icon
  export const ReplyAll: Icon
  export const Forward: Icon
  export const SwapHoriz: Icon
  export const SwapVert: Icon
  export const Shuffle: Icon
  export const Repeat: Icon
  export const Repeat1: Icon
  export const Undo: Icon
  export const Redo: Icon
  export const Ellipsis: Icon
  export const Slash: Icon
  export const Command: Icon
  export const Keyboard: Icon
  export const MousePointerClick: Icon
  export const MousePointer: Icon
  export const Hand: Icon
  export const Pointer: Icon
  export const Scan: Icon
  export const ScanLine: Icon
  export const QrCode: Icon
  export const Barcode: Icon
  export const Sigma: Icon
  export const Infinity: Icon
  export const Pi: Icon
  export const Circle: Icon
  export const Square: Icon
  export const Triangle: Icon
  export const Hexagon: Icon
  export const Octagon: Icon
  export const Pentagon: Icon
  export const Diamond: Icon
  export const Crosshair: Icon
  export const Target: Icon
  export const Ampersand: Icon
  export const AtSign: Icon
  export const Aperture: Icon
  export const CameraOff: Icon
  export const Video: Icon
  export const VideoOff: Icon
  export const Clapperboard: Icon
  export const Film: Icon
  export const Subtitles: Icon
  export const Headphones: Icon
  export const Music: Icon
  export const Piano: Icon
  export const Guitar: Icon
  export const Drum: Icon
  export const Ear: Icon
  export const EarOff: Icon
  export const Speech: Icon
  export const Text: Icon
  export const TextCursor: Icon
  export const CaseSensitive: Icon
  export const Regex: Icon
  export const Replace: Icon
  export const ReplaceAll: Icon
  export const WholeWord: Icon
  export const WrapText: Icon
  export const Pilcrow: Icon
  export const Indent: Icon
  export const Outdent: Icon
  export const AlignLeft: Icon
  export const AlignCenter: Icon
  export const AlignRight: Icon
  export const AlignJustify: Icon
  export const Bold: Icon
  export const Italic: Icon
  export const Underline: Icon
  export const Strikethrough: Icon
  export const Quote: Icon
  export const ListOrdered: Icon
  export const ListChecks: Icon
  export const Table: Icon
  export const Columns2: Icon
  export const Columns3: Icon
  export const Rows2: Icon
  export const Rows3: Icon
  export const Grid2x2: Icon
  export const Grid2x2Check: Icon
  export const Grid2x2X: Icon
  export const Grid2x2Plus: Icon
  export const Grid3x3: Icon
  export const Sheet: Icon
  export const Split: Icon
  export const Combine: Icon
  export const Ungroup: Icon
  export const Group: Icon
  export const BringToFront: Icon
  export const SendToBack: Icon
  export const Move: Icon
  export const MoveHorizontal: Icon
  export const MoveVertical: Icon
  export const ZoomIn: Icon
  export const ZoomOut: Icon
  export const Baseline: Icon
  export const Palette: Icon
  export const Paintbrush: Icon
  export const PaintBucket: Icon
  export const Eraser: Icon
  export const Pen: Icon
  export const PenLine: Icon
  export const PenTool: Icon
  export const Pencil: Icon
  export const PencilLine: Icon
  export const Highlighter: Icon
  export const Brush: Icon
  export const Pipette: Icon
  export const Ruler: Icon
  export const Compass: Icon
  export const Map: Icon
  export const MapPin: Icon
  export const MapPinned: Icon
  export const Navigation: Icon
  export const Navigation2: Icon
  export const Locate: Icon
  export const LocateFixed: Icon
  export const LocateOff: Icon
  export const Crosshair: Icon
  export const Waypoints: Icon
  export const TrendingUp: Icon
  export const TrendingDown: Icon
  export const Activity: Icon
  export const ActivitySquare: Icon
  export const BarChart: Icon
  export const BarChartHorizontal: Icon
  export const BarChart3: Icon
  export const LineChart: Icon
  export const PieChart: Icon
  export const AreaChart: Icon
  export const CandlestickChart: Icon
  export const GanttChart: Icon
  export const ScatterChart: Icon
  export const BubbleChart: Icon
  export const ChartNoAxesColumn: Icon
  export const ChartNoAxesColumnIncreasing: Icon
  export const ChartNoAxesColumnDecreasing: Icon
  export const ChartBar: Icon
  export const ChartBarStacked: Icon
  export const ChartPie: Icon
  export const ChartArea: Icon
  export const ChartLine: Icon
  export const ChartScatter: Icon
  export const ChartColumn: Icon
  export const ChartColumnStacked: Icon
  export const ChartCandlestick: Icon
  export const ChartGantt: Icon
  export const ChartNetwork: Icon
  export const ChartSpline: Icon
  export const ChartBubble: Icon
  export const ToggleLeft: Icon
  export const ToggleRight: Icon
  export const CheckSquare: Icon
  export const SquareCheck: Icon
  export const CheckCircle: Icon
  export const CircleCheck: Icon
  export const XSquare: Icon
  export const SquareX: Icon
  export const XCircle: Icon
  export const CircleX: Icon
  export const PlusSquare: Icon
  export const SquarePlus: Icon
  export const PlusCircle: Icon
  export const CirclePlus: Icon
  export const MinusSquare: Icon
  export const SquareMinus: Icon
  export const MinusCircle: Icon
  export const CircleMinus: Icon
  export const DivideSquare: Icon
  export const SquareDivide: Icon
  export const DivideCircle: Icon
  export const CircleDivide: Icon
  export const Percent: Icon
  export const Equal: Icon
  export const EqualNot: Icon
  export const NotEqual: Icon
  export const FunctionSquare: Icon
  export const Calculator: Icon
  export const Binary: Icon
  export const Variable: Icon
  export const Lambda: Icon
  export const Parentheses: Icon
  export const Brackets: Icon
  export const Braces: Icon
  export const CurlyBraces: Icon
  export const Box: Icon
  export const BoxSelect: Icon
  export const SquareUser: Icon
  export const SquareUserRound: Icon
  export const User: Icon
  export const Users: Icon
  export const UserRound: Icon
  export const UsersRound: Icon
  export const UserCheck: Icon
  export const UserPlus: Icon
  export const UserMinus: Icon
  export const UserX: Icon
  export const UserCog: Icon
  export const UserSearch: Icon
  export const Contact: Icon
  export const ContactRound: Icon
  export const Fingerprint: Icon
  export const IdCard: Icon
  export const Badge: Icon
  export const BadgeCheck: Icon
  export const BadgeX: Icon
  export const BadgeAlert: Icon
  export const BadgePlus: Icon
  export const BadgeMinus: Icon
  export const BadgeDollarSign: Icon
  export const BadgeEuro: Icon
  export const BadgePoundSterling: Icon
  export const BadgeJapaneseYen: Icon
  export const BadgeIndianRupee: Icon
  export const BadgeRussianRuble: Icon
  export const BadgeSwissFranc: Icon
  export const Verified: Icon
  export const CheckVerified: Icon
  export const Award: Icon
  export const Trophy: Icon
  export const Medal: Icon
  export const Swords: Icon
  export const Crosshair: Icon
  export const ShieldHalf: Icon
  export const ShieldCheck: Icon
  export const ShieldX: Icon
  export const ShieldBan: Icon
  export const ShieldQuestion: Icon
  export const ShieldMinus: Icon
  export const ShieldPlus: Icon
  export const Swords: Icon
  export const Axe: Icon
  export const Pickaxe: Icon
  export const Hammer: Icon
  export const Wrench: Icon
  export const Screwdriver: Icon
  export const Drill: Icon
  export const Saw: Icon
  export const FilePen: Icon
  export const FilePenLine: Icon
  export const FileEdit: Icon
  export const FilePlus: Icon
  export const FileMinus: Icon
  export const FileX: Icon
  export const FileSearch: Icon
  export const FileCog: Icon
  export const FileSpreadsheet: Icon
  export const FileJson: Icon
  export const FileType: Icon
  export const FileCode: Icon
  export const FileTerminal: Icon
  export const FileImage: Icon
  export const FileVideo: Icon
  export const FileAudio: Icon
  export const FileArchive: Icon
  export const FolderPlus: Icon
  export const FolderMinus: Icon
  export const FolderX: Icon
  export const FolderSearch: Icon
  export const FolderCog: Icon
  export const FolderTree: Icon
  export const FolderKanban: Icon
  export const FolderCheck: Icon
  export const FolderClosed: Icon
  export const FolderDot: Icon
  export const FolderInput: Icon
  export const FolderOutput: Icon
  export const FolderSymlink: Icon
  export const FolderGit: Icon
  export const FolderGit2: Icon
  export const Clipboard: Icon
  export const ClipboardList: Icon
  export const ClipboardCheck: Icon
  export const ClipboardX: Icon
  export const ClipboardCopy: Icon
  export const ClipboardPaste: Icon
  export const ClipboardPen: Icon
  export const ClipboardPenLine: Icon
  export const ClipboardEdit: Icon
  export const ClipboardType: Icon
  export const ClipboardMinus: Icon
  export const ClipboardPlus: Icon
  export const ClipboardSignature: Icon
  export const Scroll: Icon
  export const ScrollText: Icon
  export const AudioLines: Icon
  export const AudioWaveform: Icon
  export const Waves: Icon
  export const Waveform: Icon
  export const Sigma: Icon
  export const CaseLower: Icon
  export const CaseUpper: Icon
  export const Tractor: Icon
  export const Combine: Icon
  export const Ungroup: Icon
  export const Group: Icon
  export const BringToFront: Icon
  export const SendToBack: Icon
  export const Move: Icon
  export const MoveDiagonal: Icon
  export const MoveDiagonal2: Icon
  export const MoveHorizontal: Icon
  export const MoveVertical: Icon
  export const ZoomIn: Icon
  export const ZoomOut: Icon
  export const Maximize: Icon
  export const Minimize: Icon
  export const Expand: Icon
  export const Shrink: Icon
  export const Baseline: Icon
  export const Palette: Icon
  export const Paintbrush: Icon
  export const PaintbrushVertical: Icon
  export const PaintBucket: Icon
  export const Eraser: Icon
  export const Pen: Icon
  export const PenTool: Icon
  export const Pencil: Icon
  export const PencilRuler: Icon
  export const PencilLine: Icon
  export const Highlighter: Icon
  export const Brush: Icon
  export const Pipette: Icon
  export const Ruler: Icon
  export const Compass: Icon
  export const Map: Icon
  export const MapPin: Icon
  export const MapPinned: Icon
  export const Navigation: Icon
  export const Navigation2: Icon
  export const Locate: Icon
  export const LocateFixed: Icon
  export const LocateOff: Icon
  export const Crosshair: Icon
  export const Waypoints: Icon
  export const TrendingUp: Icon
  export const TrendingDown: Icon
  export const Activity: Icon
  export const ActivitySquare: Icon
  export const BarChart: Icon
  export const BarChartHorizontal: Icon
  export const BarChart3: Icon
  export const LineChart: Icon
  export const PieChart: Icon
  export const AreaChart: Icon
  export const CandlestickChart: Icon
  export const GanttChart: Icon
  export const ScatterChart: Icon
  export const BubbleChart: Icon
  export const ChartNoAxesColumn: Icon
  export const ChartNoAxesColumnIncreasing: Icon
  export const ChartNoAxesColumnDecreasing: Icon
  export const ChartBar: Icon
  export const ChartBarStacked: Icon
  export const ChartPie: Icon
  export const ChartArea: Icon
  export const ChartLine: Icon
  export const ChartScatter: Icon
  export const ChartColumn: Icon
  export const ChartColumnStacked: Icon
  export const ChartCandlestick: Icon
  export const ChartGantt: Icon
  export const ChartNetwork: Icon
  export const ChartSpline: Icon
  export const ChartBubble: Icon
  export const ToggleLeft: Icon
  export const ToggleRight: Icon
  export const CheckSquare: Icon
  export const SquareCheck: Icon
  export const CheckCircle: Icon
  export const CircleCheck: Icon
  export const XSquare: Icon
  export const SquareX: Icon
  export const XCircle: Icon
  export const CircleX: Icon
  export const PlusSquare: Icon
  export const SquarePlus: Icon
  export const PlusCircle: Icon
  export const CirclePlus: Icon
  export const MinusSquare: Icon
  export const SquareMinus: Icon
  export const MinusCircle: Icon
  export const CircleMinus: Icon
  export const DivideSquare: Icon
  export const SquareDivide: Icon
  export const DivideCircle: Icon
  export const CircleDivide: Icon
  export const Percent: Icon
  export const Equal: Icon
  export const EqualNot: Icon
  export const NotEqual: Icon
  export const FunctionSquare: Icon
  export const Calculator: Icon
  export const Binary: Icon
  export const Variable: Icon
  export const Lambda: Icon
  export const Parentheses: Icon
  export const Brackets: Icon
  export const Braces: Icon
  export const CurlyBraces: Icon
  export const Box: Icon
  export const BoxSelect: Icon
  export const SquareUser: Icon
  export const SquareUserRound: Icon
  export const User: Icon
  export const Users: Icon
  export const UserRound: Icon
  export const UsersRound: Icon
  export const UserCheck: Icon
  export const UserPlus: Icon
  export const UserMinus: Icon
  export const UserX: Icon
  export const UserCog: Icon
  export const UserSearch: Icon
  export const Contact: Icon
  export const ContactRound: Icon
  export const Fingerprint: Icon
  export const IdCard: Icon
  export const Badge: Icon
  export const BadgeCheck: Icon
  export const BadgeX: Icon
  export const BadgeAlert: Icon
  export const BadgePlus: Icon
  export const BadgeMinus: Icon
  export const BadgeDollarSign: Icon
  export const BadgeEuro: Icon
  export const BadgePoundSterling: Icon
  export const BadgeJapaneseYen: Icon
  export const BadgeIndianRupee: Icon
  export const BadgeRussianRuble: Icon
  export const BadgeSwissFranc: Icon
  export const Verified: Icon
  export const CheckVerified: Icon
  export const Award: Icon
  export const Trophy: Icon
  export const Medal: Icon
  export const Swords: Icon
  export const Crosshair: Icon
  export const ShieldHalf: Icon
  export const ShieldCheck: Icon
  export const ShieldX: Icon
  export const ShieldBan: Icon
  export const ShieldQuestion: Icon
  export const ShieldMinus: Icon
  export const ShieldPlus: Icon
  export const Swords: Icon
  export const Axe: Icon
  export const Pickaxe: Icon
  export const Hammer: Icon
  export const Wrench: Icon
  export const Screwdriver: Icon
  export const Drill: Icon
  export const Saw: Icon
  export const FilePen: Icon
  export const FilePenLine: Icon
  export const FileEdit: Icon
  export const FilePlus: Icon
  export const FileMinus: Icon
  export const FileX: Icon
  export const FileSearch: Icon
  export const FileCog: Icon
  export const FileSpreadsheet: Icon
  export const FileJson: Icon
  export const FileType: Icon
  export const FileCode: Icon
  export const FileTerminal: Icon
  export const FileImage: Icon
  export const FileVideo: Icon
  export const FileAudio: Icon
  export const FileArchive: Icon
  export const FolderPlus: Icon
  export const FolderMinus: Icon
  export const FolderX: Icon
  export const FolderSearch: Icon
  export const FolderCog: Icon
  export const FolderTree: Icon
  export const FolderKanban: Icon
  export const FolderCheck: Icon
  export const FolderClosed: Icon
  export const FolderDot: Icon
  export const FolderInput: Icon
  export const FolderOutput: Icon
  export const FolderSymlink: Icon
  export const FolderGit: Icon
  export const FolderGit2: Icon
  export const Clipboard: Icon
  export const ClipboardList: Icon
  export const ClipboardCheck: Icon
  export const ClipboardX: Icon
  export const ClipboardCopy: Icon
  export const ClipboardPaste: Icon
  export const ClipboardPen: Icon
  export const ClipboardPenLine: Icon
  export const ClipboardEdit: Icon
  export const ClipboardType: Icon
  export const ClipboardMinus: Icon
  export const ClipboardPlus: Icon
  export const ClipboardSignature: Icon
  export const Scroll: Icon
  export const ScrollText: Icon
  export const AudioLines: Icon
  export const AudioWaveform: Icon
  export const Waves: Icon
  export const Waveform: Icon
  export const Sigma: Icon
  export const CaseLower: Icon
  export const CaseUpper: Icon
  export const CaseSensitive: Icon
  export const MousePointerClick: Icon
  export const MousePointerBan: Icon
  export const MousePointer2: Icon
  export const Pointer: Icon
  export const Hand: Icon
  export const Scan: Icon
  export const ScanEye: Icon
  export const ScanFace: Icon
  export const ScanLine: Icon
  export const ScanSearch: Icon
  export const ScanText: Icon
  export const Scanner: Icon
  export const QrCode: Icon
  export const Barcode: Icon
  export const Keyboard: Icon
  export const KeyboardMusic: Icon
  export const Command: Icon
  export const Slash: Icon
  export const Ellipsis: Icon
  export const ForkKnife: Icon
  export const ForkKnifeCross: Icon
  export const ChefHat: Icon
  export const CookingPot: Icon
  export const Soup: Icon
  export const Utensils: Icon
  export const UtensilsCrossed: Icon
  export const Croissant: Icon
  export const CakeSlice: Icon
  export const Cookie: Icon
  export const Candy: Icon
  export const CandyCane: Icon
  export const Apple: Icon
  export const Citrus: Icon
  export const Grape: Icon
  export const Banana: Icon
  export const Cherry: Icon
  export const Strawberry: Icon
  export const Egg: Icon
  export const EggFried: Icon
  export const Milk: Icon
  export const Beer: Icon
  export const BeerOff: Icon
  export const Wine: Icon
  export const WineOff: Icon
  export const Coffee: Icon
  export const Mocha: Icon
  export const CupSoda: Icon
  export const Bottle: Icon
  export const GlassWater: Icon
  export const Droplet: Icon
  export const Droplets: Icon
  export const Waves: Icon
  export const Floodlight: Icon
  export const Lightbulb: Icon
  export const LightbulbOff: Icon
  export const Lamp: Icon
  export const LampCeiling: Icon
  export const LampDesk: Icon
  export const LampFloor: Icon
  export const LampWallDown: Icon
  export const LampWallUp: Icon
  export const Fan: Icon
  export const FanAuto: Icon
  export const Refrigerator: Icon
  export const Oven: Icon
  export const Microwave: Icon
  export const Toaster: Icon
  export const WashingMachine: Icon
  export const Dryer: Icon
  export const AirVent: Icon
  export const Airplay: Icon
  export const AlarmCheck: Icon
  export const AlarmClock: Icon
  export const AlarmClockCheck: Icon
  export const AlarmClockMinus: Icon
  export const AlarmClockOff: Icon
  export const AlarmClockPlus: Icon
  export const AlarmSmoke: Icon
  export const Ambulance: Icon
  export const Shield: Icon
  export const ShieldAlert: Icon
  export const ShieldBan: Icon
  export const ShieldCheck: Icon
  export const ShieldEllipsis: Icon
  export const ShieldHalf: Icon
  export const ShieldMinus: Icon
  export const ShieldOff: Icon
  export const ShieldPlus: Icon
  export const ShieldQuestion: Icon
  export const ShieldX: Icon
  export const Swords: Icon
  export const Axe: Icon
  export const Pickaxe: Icon
  export const Hammer: Icon
  export const Wrench: Icon
  export const Screwdriver: Icon
  export const Drill: Icon
  export const Saw: Icon
  export const Nut: Icon
  export const NutOff: Icon
  export const Bug: Icon
  export const BugOff: Icon
  export const BugPlay: Icon
  export const Antenna: Icon
  export const AntennaOff: Icon
  export const Wifi: Icon
  export const WifiHigh: Icon
  export const WifiLow: Icon
  export const WifiZero: Icon
  export const WifiOff: Icon
  export const Bluetooth: Icon
  export const BluetoothConnected: Icon
  export const BluetoothOff: Icon
  export const BluetoothSearching: Icon
  export const Satellite: Icon
  export const SatelliteDish: Icon
  export const Radio: Icon
  export const RadioReceiver: Icon
  export const RadioTower: Icon
  export const Podcast: Icon
  export const Tv: Icon
  export const Tv2: Icon
  export const Monitor: Icon
  export const MonitorCheck: Icon
  export const MonitorDot: Icon
  export const MonitorDot: Icon
  export const MonitorDown: Icon
  export const MonitorOff: Icon
  export const MonitorPause: Icon
  export const MonitorPlay: Icon
  export const MonitorSmartphone: Icon
  export const MonitorSpeaker: Icon
  export const MonitorStop: Icon
  export const MonitorUp: Icon
  export const MonitorX: Icon
  export const Smartphone: Icon
  export const SmartphoneCharging: Icon
  export const SmartphoneNfc: Icon
  export const Tablet: Icon
  export const TabletSmartphone: Icon
  export const Laptop: Icon
  export const LaptopMinimal: Icon
  export const HardDrive: Icon
  export const HardDriveDownload: Icon
  export const HardDriveUpload: Icon
  export const Printer: Icon
  export const PrinterCheck: Icon
  export const Projector: Icon
  export const ScanBarcode: Icon
  export const ScanEye: Icon
  export const ScanFace: Icon
  export const ScanLine: Icon
  export const ScanQrCode: Icon
  export const ScanSearch: Icon
  export const ScanText: Icon
  export const Scissors: Icon
  export const ScissorsLineDashed: Icon
  export const ScreenShare: Icon
  export const ScreenShareOff: Icon
  export const SdCard: Icon
  export const Server: Icon
  export const ServerCog: Icon
  export const ServerCrash: Icon
  export const ServerOff: Icon
  export const Shapes: Icon
  export const Share: Icon
  export const Share2: Icon
  export const Sheet: Icon
  export const Shell: Icon
  export const Shield: Icon
  export const Ship: Icon
  export const ShipWheel: Icon
  export const ShoppingBag: Icon
  export const ShoppingBasket: Icon
  export const ShoppingCart: Icon
  export const Shovel: Icon
  export const ShowerHead: Icon
  export const Shrink: Icon
  export const Shrub: Icon
  export const Shuffle: Icon
  export const Sigma: Icon
  export const Signpost: Icon
  export const SignpostBig: Icon
  export const Siren: Icon
  export const SkipBack: Icon
  export const SkipForward: Icon
  export const Skull: Icon
  export const Slack: Icon
  export const Slash: Icon
  export const Slice: Icon
  export const SlidersHorizontal: Icon
  export const SlidersVertical: Icon
  export const Smartphone: Icon
  export const SmartphoneCharging: Icon
  export const SmartphoneNfc: Icon
  export const Smile: Icon
  export const SmilePlus: Icon
  export const Snail: Icon
  export const Snowflake: Icon
  export const Soap: Icon
  export const Soccer: Icon
  export const SortAsc: Icon
  export const SortDesc: Icon
  export const Speaker: Icon
  export const Speech: Icon
  export const SpellCheck: Icon
  export const SpellCheck2: Icon
  export const Spline: Icon
  export const Split: Icon
  export const SprayCan: Icon
  export const Sprout: Icon
  export const Square: Icon
  export const SquareActivity: Icon
  export const SquareArrowDown: Icon
  export const SquareArrowDownLeft: Icon
  export const SquareArrowDownRight: Icon
  export const SquareArrowLeft: Icon
  export const SquareArrowRight: Icon
  export const SquareArrowUp: Icon
  export const SquareArrowUpLeft: Icon
  export const SquareArrowUpRight: Icon
  export const SquareAsterisk: Icon
  export const SquareCheck: Icon
  export const SquareCheckBig: Icon
  export const SquareChevronDown: Icon
  export const SquareChevronLeft: Icon
  export const SquareChevronRight: Icon
  export const SquareChevronUp: Icon
  export const SquareCode: Icon
  export const SquareDashed: Icon
  export const SquareDashedBottom: Icon
  export const SquareDashedBottomCode: Icon
  export const SquareDashedKanban: Icon
  export const SquareDashedMousePointer: Icon
  export const SquareDivide: Icon
  export const SquareDot: Icon
  export const SquareEqual: Icon
  export const SquareFunction: Icon
  export const SquareKanban: Icon
  export const SquareLibrary: Icon
  export const SquareM: Icon
  export const SquareMenu: Icon
  export const SquareMinus: Icon
  export const SquareMousePointer: Icon
  export const SquareParking: Icon
  export const SquareParkingOff: Icon
  export const SquarePen: Icon
  export const SquarePercent: Icon
  export const SquarePi: Icon
  export const SquarePlus: Icon
  export const SquarePower: Icon
  export const SquareRadical: Icon
  export const SquareScissors: Icon
  export const SquareSigma: Icon
  export const SquareSlash: Icon
  export const SquareSplitHorizontal: Icon
  export const SquareSplitVertical: Icon
  export const SquareSquare: Icon
  export const SquareStack: Icon
  export const SquareTerminal: Icon
  export const SquareUser: Icon
  export const SquareUserRound: Icon
  export const SquareX: Icon
  export const Squirrel: Icon
  export const Stamp: Icon
  export const Star: Icon
  export const StarHalf: Icon
  export const StarOff: Icon
  export const Stars: Icon
  export const StepBack: Icon
  export const StepForward: Icon
  export const Stethoscope: Icon
  export const Sticker: Icon
  export const StickyNote: Icon
  export const StopCircle: Icon
  export const Store: Icon
  export const StretchHorizontal: Icon
  export const StretchVertical: Icon
  export const Strikethrough: Icon
  export const Subscript: Icon
  export const Subtitles: Icon
  export const Sun: Icon
  export const SunDim: Icon
  export const SunMedium: Icon
  export const SunMoon: Icon
  export const SunSnow: Icon
  export const Sunrise: Icon
  export const Sunset: Icon
  export const Superscript: Icon
  export const SwatchBook: Icon
  export const SwissFranc: Icon
  export const SwitchCamera: Icon
  export const Sword: Icon
  export const Swords: Icon
  export const Syringe: Icon
  export const Table: Icon
  export const Table2: Icon
  export const TableCellsMerge: Icon
  export const TableCellsSplit: Icon
  export const TableColumnsSplit: Icon
  export const TableOfContents: Icon
  export const TableProperties: Icon
  export const TableRowsSplit: Icon
  export const Tablet: Icon
  export const TabletSmartphone: Icon
  export const Tablets: Icon
  export const Tag: Icon
  export const Tags: Icon
  export const Tally1: Icon
  export const Tally2: Icon
  export const Tally3: Icon
  export const Tally4: Icon
  export const Tally5: Icon
  export const Tangent: Icon
  export const Target: Icon
  export const Telescope: Icon
  export const Tent: Icon
  export const TentTree: Icon
  export const Terminal: Icon
  export const TestTube: Icon
  export const TestTube2: Icon
  export const TestTubes: Icon
  export const Text: Icon
  export const TextCursor: Icon
  export const TextCursorInput: Icon
  export const TextQuote: Icon
  export const TextSearch: Icon
  export const TextSelect: Icon
  export const TextSelection: Icon
  export const Theater: Icon
  export const Thermometer: Icon
  export const ThermometerSnowflake: Icon
  export const ThermometerSun: Icon
  export const ThumbsDown: Icon
  export const ThumbsUp: Icon
  export const Ticket: Icon
  export const TicketCheck: Icon
  export const TicketMinus: Icon
  export const TicketPercent: Icon
  export const TicketPlus: Icon
  export const TicketSlash: Icon
  export const TicketX: Icon
  export const Timer: Icon
  export const TimerOff: Icon
  export const TimerReset: Icon
  export const ToggleLeft: Icon
  export const ToggleRight: Icon
  export const Tornado: Icon
  export const Torus: Icon
  export const Touchpad: Icon
  export const TouchpadOff: Icon
  export const TowerControl: Icon
  export const ToyBrick: Icon
  export const Tractor: Icon
  export const TrafficCone: Icon
  export const Train: Icon
  export const TrainTrack: Icon
  export const TramFront: Icon
  export const Trash: Icon
  export const Trash2: Icon
  export const TreeDeciduous: Icon
  export const TreePine: Icon
  export const Trees: Icon
  export const Trello: Icon
  export const TrendingDown: Icon
  export const TrendingUp: Icon
  export const TrendingUpDown: Icon
  export const Triangle: Icon
  export const TriangleAlert: Icon
  export const TriangleRight: Icon
  export const Trophy: Icon
  export const Truck: Icon
  export const Turtle: Icon
  export const Tv: Icon
  export const TvMinimal: Icon
  export const TvMinimalPlay: Icon
  export const Twitch: Icon
  export const Twitter: Icon
  export const Type: Icon
  export const Umbrella: Icon
  export const UmbrellaOff: Icon
  export const Underline: Icon
  export const Undo: Icon
  export const Undo2: Icon
  export const UndoDot: Icon
  export const UnfoldHorizontal: Icon
  export const UnfoldVertical: Icon
  export const Ungroup: Icon
  export const University: Icon
  export const Unlink: Icon
  export const Unlink2: Icon
  export const Unlock: Icon
  export const Unplug: Icon
  export const Upload: Icon
  export const Usb: Icon
  export const User: Icon
  export const UserCheck: Icon
  export const UserCog: Icon
  export const UserMinus: Icon
  export const UserPlus: Icon
  export const UserRound: Icon
  export const UserRoundCheck: Icon
  export const UserRoundCog: Icon
  export const UserRoundMinus: Icon
  export const UserRoundPlus: Icon
  export const UserRoundSearch: Icon
  export const UserRoundX: Icon
  export const UserSearch: Icon
  export const UserX: Icon
  export const Users: Icon
  export const UsersRound: Icon
  export const Utensils: Icon
  export const UtensilsCrossed: Icon
  export const UtilityPole: Icon
  export const Variable: Icon
  export const Vault: Icon
  export const Vegan: Icon
  export const VenetianMask: Icon
  export const Verified: Icon
  export const Vibrate: Icon
  export const VibrateOff: Icon
  export const Video: Icon
  export const VideoOff: Icon
  export const Videotape: Icon
  export const View: Icon
  export const Voicemail: Icon
  export const Volume: Icon
  export const Volume1: Icon
  export const Volume2: Icon
  export const VolumeX: Icon
  export const Vote: Icon
  export const Wallet: Icon
  export const WalletCards: Icon
  export const WalletMinimal: Icon
  export const Wallpaper: Icon
  export const Wand: Icon
  export const WandSparkles: Icon
  export const Warehouse: Icon
  export const WashingMachine: Icon
  export const Watch: Icon
  export const Waves: Icon
  export const Waypoints: Icon
  export const Webcam: Icon
  export const Webhook: Icon
  export const WebhookOff: Icon
  export const Weight: Icon
  export const Wheat: Icon
  export const WheatOff: Icon
  export const WholeWord: Icon
  export const Wifi: Icon
  export const WifiHigh: Icon
  export const WifiLow: Icon
  export const WifiOff: Icon
  export const WifiZero: Icon
  export const Wind: Icon
  export const Wine: Icon
  export const WineOff: Icon
  export const Workflow: Icon
  export const WrapText: Icon
  export const Wrench: Icon
  export const X: Icon
  export const XCircle: Icon
  export const XOctagon: Icon
  export const XSquare: Icon
  export const Youtube: Icon
  export const Zap: Icon
  export const ZapOff: Icon
  export const ZoomIn: Icon
  export const ZoomOut: Icon

  export default Icon
}