import { ArrowRight, ArrowDown, Monitor, ShieldCheck, Server, Globe, MessageSquare, Folder, Check, Wrench, Plug, type LucideIcon } from 'lucide-react';
type Kind = 'architecture' | 'task' | 'permissions' | 'mcp' | 'message';
type Node = {title:string;detail:string;icon:LucideIcon;tone?:string};
const flows:Record<Exclude<Kind,'architecture'>,{title:string;caption:string;nodes:Node[]}>={
 task:{title:'De la intención a un resultado verificable',caption:'La revisión del resultado cierra el flujo; una respuesta del modelo por sí sola no verifica un cambio.',nodes:[{title:'Delimita',detail:'Objetivo, carpeta y alcance',icon:Folder},{title:'Pide una propuesta',detail:'Lectura y explicación inicial',icon:MessageSquare},{title:'Autoriza',detail:'Según el modo de permisos',icon:ShieldCheck,tone:'sand'},{title:'Ejecuta',detail:'Herramientas y sus resultados',icon:Wrench},{title:'Comprueba',detail:'Diff, archivos y pruebas',icon:Check,tone:'green'}]},
 permissions:{title:'Ruta de una acción permitida',caption:'Si la política bloquea una llamada o rechazas su aprobación, esa llamada no debe continuar a la ejecución. Los efectos ya realizados requieren una revisión aparte.',nodes:[{title:'Solicitud',detail:'Herramienta y argumentos',icon:Wrench},{title:'Política',detail:'Alcance y modo de permisos',icon:ShieldCheck,tone:'sand'},{title:'Aprobación',detail:'Cuando la política la exige',icon:Check,tone:'sand'},{title:'Ejecución',detail:'Operación autorizada',icon:Server},{title:'Resultado',detail:'Salida, error o cancelación',icon:MessageSquare,tone:'green'}]},
 mcp:{title:'Cómo se conecta una herramienta MCP',caption:'El servidor puede ser un proceso local o un servicio remoto. La autenticación y los permisos dependen de la integración.',nodes:[{title:'Sparta',detail:'Cliente y tarea del usuario',icon:Monitor},{title:'Permisos',detail:'Llamada y alcance autorizado',icon:ShieldCheck,tone:'sand'},{title:'Servidor MCP',detail:'Transporte y autenticación',icon:Plug,tone:'violet'},{title:'Herramienta',detail:'Operación y resultado',icon:Wrench},{title:'Conversación',detail:'Resultado como contexto',icon:MessageSquare,tone:'green'}]},
 message:{title:'Qué ocurre al enviar un mensaje',caption:'El contenido incluido en una solicitud viaja al proveedor seleccionado. La respuesta llega de forma progresiva; las herramientas siguen su propia política.',nodes:[{title:'Contexto',detail:'Mensaje y archivos elegidos',icon:Folder},{title:'Backend',detail:'Sesión y preparación',icon:Server},{title:'Proveedor API',detail:'Procesa la solicitud',icon:Globe,tone:'violet'},{title:'Streaming',detail:'Texto, razonamiento y llamadas',icon:MessageSquare},{title:'Interfaz',detail:'Muestra partes y estados',icon:Monitor,tone:'green'}]},
};
function Tile({node}:{node:Node}){return <div className={'docs-diagram-node '+(node.tone??'neutral')}><node.icon aria-hidden="true"/><strong>{node.title}</strong><span>{node.detail}</span></div>}
export function DocsDiagram({type='task'}:{type?:Kind}){
 if(type==='architecture')return <figure className="docs-diagram" aria-label="Arquitectura del escritorio y frontera con servicios externos"><header><span className="docs-diagram-kicker">MAPA DEL SISTEMA</span><strong>Control local, proveedores por API</strong></header><div className="docs-diagram-boundary"><span className="docs-diagram-boundary-title"><Monitor size={14}/>En tu equipo</span><div className="docs-architecture-grid"><Tile node={{title:'Frontend React',detail:'Conversaciones, estado y presentación',icon:Monitor}}/><Tile node={{title:'Electron + preload',detail:'Ventana, IPC y operaciones de escritorio',icon:ShieldCheck,tone:'sand'}}/><Tile node={{title:'Backend Python',detail:'API, sesión, herramientas y persistencia',icon:Server}}/></div><div className="docs-diagram-channels"><span>React ↔ Electron: IPC acotado</span><span>React ↔ Python: HTTP autenticado</span><span>Electron → Python: ciclo de vida del motor</span></div></div><div className="docs-diagram-outbound"><ArrowDown aria-hidden="true"/><span>Solicitud al proveedor y respuesta progresiva</span></div><div className="docs-diagram-remote"><Tile node={{title:'Proveedor o servidor API compatible',detail:'Modelo configurado; infraestructura gestionada fuera del instalador de Sparta',icon:Globe,tone:'violet'}}/></div><figcaption>Una API compatible puede estar en tu PC o red. Esta edición no incorpora la administración de pesos ni motores de modelos locales.</figcaption></figure>;
 const flow=flows[type];return <figure className="docs-diagram" aria-label={flow.title}><header><span className="docs-diagram-kicker">FLUJO DE TRABAJO</span><strong>{flow.title}</strong></header><ol className="docs-flow">{flow.nodes.map((node,index)=><li key={node.title}><span className="docs-flow-number">{String(index+1).padStart(2,'0')}</span><Tile node={node}/>{index<flow.nodes.length-1&&<ArrowRight className="docs-flow-arrow" aria-hidden="true"/>}</li>)}</ol><figcaption>{flow.caption}</figcaption></figure>;
}
