import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const pagesDir = path.join(root, 'src/components/docs/content/pages');
function walk(dir) {
  return readdirSync(dir, { withFileTypes: true }).flatMap(entry => entry.isDirectory() ? walk(path.join(dir, entry.name)) : entry.name.endsWith('.mdx') ? [path.join(dir, entry.name)] : []);
}
export function generateDocsCatalog() {
  const pages = walk(pagesDir).map(file => {
    const raw = readFileSync(file, 'utf8').replace(/\r\n/g, '\n');
    const slug = path.relative(pagesDir, file).replaceAll('\\', '/').replace(/\.mdx$/, '');
    const title = raw.match(/^title:\s*(.+)$/m)?.[1]?.replace(/^['"]|['"]$/g, '');
    const description = raw.match(/^description:\s*(.+)$/m)?.[1]?.replace(/^['"]|['"]$/g, '') ?? '';
    if (!title) throw new Error(`Missing title: ${slug}`);
    const text = raw.replace(/^---\n[\s\S]*?\n---/, '').replace(/^import .*$/gm, '').replace(/<[^>]*>/g, ' ').replace(/[#*`{}]/g, '').replace(/\s+/g, ' ').trim();
    return { slug, title, description, text };
  });
  const output = `// Generated by scripts/docs-catalog.mjs from the MDX source.\nexport const catalog = ${JSON.stringify(pages, null, 2)};\n`;
  const target = path.join(root, 'src/components/docs/lib/catalog.generated.ts');
  mkdirSync(path.dirname(target), { recursive: true });
  let previous = '';
  try { previous = readFileSync(target, 'utf8'); } catch {}
  if (previous !== output) writeFileSync(target, output);
  return pages;
}
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) console.log(`Indexed ${generateDocsCatalog().length} documentation pages`);
