"""Modular package for model management routes and helpers."""

from fastapi import APIRouter

from routes.models_pkg.schemas import (
    CachedModelRepo,
    CachedModelsResponse,
    _CompatLocalInventorySources,
    _CompatLocalInventoryKey,
    _COMPAT_LOCAL_INVENTORY_MAX_ATTEMPTS,
    _CompatLocalCacheChanged,
    CachedModelPathResponse,
)
from routes.models_pkg.helpers_paths import (
    _VALID_REPO_ID,
    _is_valid_repo_id,
    _normalize_hf_token,
    _safe_is_dir,
    hidden_model_matchers,
    _resolve_hf_cache_dir,
    _is_model_directory,
    _dir_has_downloaded_model,
    _BROWSE_MODEL_HINT_PROBE,
    _BROWSE_ENTRY_CAP,
    _count_model_files,
    _has_direct_model_signal,
    _looks_like_model_dir,
    _build_browse_allowlist,
    _is_path_inside_allowlist,
    _normalize_browse_request_path,
    _browse_relative_parts,
    _match_browse_child,
    _resolve_browse_target,
    _is_path_under,
    _is_path_under_lexically,
    _loaded_model_matches_deleted_path,
    _loading_model_matches_deleted_path,
    _active_diffusion_backend,
    _active_video_backend,
    _prune_empty_parents,
    _variant_names_same_checkpoint,
    _delete_gguf_variant_files,
    _resolve_hf_cache_realpath,
    _repo_in_any_hf_cache,
    _all_hf_cache_scans,
    _loaded_id_matches_repo,
    _resolve_cached_model_path,
    _is_sizable_local_path,
    _export_size_cached,
)
from routes.models_pkg.helpers_detection import (
    derive_model_type,
    _WEIGHT_BIN_PREFIXES,
    _is_weight_bin,
    _has_non_gguf_weights,
    _local_pipeline_index,
    _is_gguf_companion_only_dir,
    _looks_like_mlx_repo,
    _get_max_position_embeddings,
    _MODEL_WEIGHT_EXTENSIONS,
    _get_model_size_bytes,
    _get_snapshot_model_size_bytes,
    _model_config_inspection_target,
    _consent_provider,
    _audio_probe_target,
    _audio_type_of_checkpoint,
    _NATIVE_CONTEXT_READ_TIMEOUT_SECONDS,
    _NATIVE_CONTEXT_HARD_TIMEOUT_SECONDS,
    _NATIVE_CONTEXT_MAX_CONCURRENT_READS,
    _native_context_slots,
    _settle_native_context,
    _read_native_context_length_bounded,
    _read_native_context_length,
    _resolve_quant_gguf,
    _is_gguf_filename,
    _is_mmproj_filename,
    _is_main_gguf_filename,
    _recovered_repo_is_unusable_by_repo_id,
    _repo_id_will_not_resolve,
    _default_ref_offers_no_whole_quant,
    _gguf_copy_is_usable,
    _snapshot_has_gguf_projector,
    _cached_repo_file_name,
    _main_variant_gguf_label,
    _one_shard_family_of,
    _main_variant_rank,
    _variant_keys_match,
    _normalized_quant_label,
    _repo_has_mmproj,
    _cached_gguf_row_has_vision,
    _iter_gguf_paths,
    _repo_gguf_size_bytes,
    _repo_has_gguf_files,
    _blob_mtime,
    _repo_gguf_last_modified,
    _DIFFUSION_GGUF_ARCHS,
    _UNSUPPORTED_DIFFUSION_GGUF_ARCHS,
    _AMBIGUOUS_DIFFUSION_GGUF_ARCHS,
    _PLACEHOLDER_DIFFUSION_GGUF_ARCHS,
    _VIDEO_GGUF_ARCHS,
    _VIDEO_GEN_TASK,
    _UNSUPPORTED_DIFFUSION_TASK,
    _H3_DENOISER_GGUF_PREFIXES,
    _is_h3_bundle_gguf_hint,
    _gguf_architecture,
    _gguf_family_buildable,
    _video_family_buildable,
    _arch_to_task,
    _LOADABLE_MEDIA_GGUF_TASKS,
    _MAX_TASK_CLASSIFY_GGUFS,
    _TASK_CLASSIFY_WALK_SECONDS,
    _TASK_CLASSIFY_READ_SECONDS,
    _is_trailing_split_shard,
    _task_classify_sort_key,
    _gguf_folder_task,
    _repo_gguf_task,
    _hf_cache_snapshot_repo_id,
    _local_family_needles,
    _local_model_task,
    _local_is_diffusers,
    snapshot_variants_all_complete,
    snapshot_has_complete_variants,
    _repo_gguf_load_id,
    _preferred_gguf_copy,
    _repo_has_pipeline_index,
    _repo_is_diffusers,
    _repo_pipeline_missing_denoiser,
    _cached_repo_partial,
    _is_sd_cpp_companion_repo,
    _cached_repo_task,
)
from routes.models_pkg.router_local import (
    router as _router_local,
    _scan_models_dir,
    _scan_hf_cache,
    _dir_model_format,
    _scan_lmstudio_dir,
    _ollama_links_dir,
    _scan_ollama_dir,
    _compat_local_inventory_sources,
    collect_local_models,
    _compat_inventory_path_identity,
    _shared_compat_local_inventory_scan,
    list_local_models,
    get_scan_folders,
    add_scan_folder_endpoint,
    remove_scan_folder_endpoint,
    get_recommended_folders,
    browse_folders,
)
from routes.models_pkg.router_catalog import (
    router as _router_catalog,
    list_models,
    get_model_config,
    check_vision_model,
    check_embedding_model,
)
from routes.models_pkg.router_security import (
    router as _router_security,
    scan_model_remote_code,
    discard_remote_code_download,
)
from routes.models_pkg.router_loras import (
    router as _router_loras,
    scan_loras,
    _scan_loras_sync,
    scan_diffusion_loras,
    scan_diffusion_controlnets,
    delete_finetuned_model,
    get_lora_base_model,
)
from routes.models_pkg.router_gguf import (
    router as _router_gguf,
    get_kv_cache_estimate,
    get_gguf_variants,
    get_gguf_download_progress,
    get_download_progress,
)
from routes.models_pkg.router_cached import (
    router as _router_cached,
    list_cached_gguf,
    list_cached_models,
    delete_cached_model,
    get_cached_model_path,
    reveal_cached_model,
    list_checkpoints,
    get_export_size,
)

router = APIRouter()
for sub_router in (
    _router_local,
    _router_catalog,
    _router_security,
    _router_loras,
    _router_gguf,
    _router_cached,
):
    for r in sub_router.routes:
        router.routes.append(r)
